server/src/main/java/com/lucky7/preproject/question/controller/QuestionController.java

Fix: "CORS 어노테이션 추가"

---

client/src/components/Nav.jsx

feat: Nav.jsx 파일 생성

---

server/src/main/java/com/lucky7/preproject/answer/entity/Answer.java
server/src/main/java/com/lucky7/preproject/comment/entity/AnswerComment.java
server/src/main/java/com/lucky7/preproject/comment/entity/QuestionComment.java
server/src/main/java/com/lucky7/preproject/question/entity/Question.java
server/src/main/java/com/lucky7/preproject/user/entity/User.java

feat: 엔티티 클래스 생성
서비스 계층에 사용할 엔티티 클래스 입니다
추가된 클래스는 아래와 같습니다
Question / Answer / QuestionComment / AnswerComment / User
Resolves: #8

엔티티 클래스 생성

---

client/src/components/Nav.jsx

클릭 했을 때 경로변경 및 백그라운드 수정 추가 했습니다.

fix: Nav.jsx 수정 

---

server/src/main/java/com/lucky7/preproject/comment/controller/AnswerCommentController.java
server/src/main/java/com/lucky7/preproject/comment/controller/QuestionCommentController.java
server/src/main/java/com/lucky7/preproject/comment/dto/AnswerCommentResponseDto.java
server/src/main/java/com/lucky7/preproject/comment/dto/CommentRequestDto.java
server/src/main/java/com/lucky7/preproject/comment/dto/QuestionCommentResponseDto.java
server/src/main/java/com/lucky7/preproject/comment/entity/AnswerComment.java
server/src/main/java/com/lucky7/preproject/comment/mapper/CommentMapper.java
server/src/main/java/com/lucky7/preproject/comment/service/AnswerCommentService.java
server/src/main/java/com/lucky7/preproject/comment/service/QuestionCommentService.java
server/src/main/java/com/lucky7/preproject/user/entity/User.java
server/src/main/resources/application.yml

Comment 관련 api 기능 구현 및 테스트 완료했습니다.
Resolves: #6, #13

feat: Comment Controller 및 Service 구현

---

server/src/main/java/com/lucky7/preproject/answer/entity/Answer.java
server/src/main/java/com/lucky7/preproject/comment/controller/QuestionCommentController.java
server/src/main/java/com/lucky7/preproject/comment/entity/AnswerComment.java
server/src/main/java/com/lucky7/preproject/comment/entity/QuestionComment.java
server/src/main/java/com/lucky7/preproject/question/controller/QuestionController.java
server/src/main/java/com/lucky7/preproject/question/entity/Question.java
server/src/main/java/com/lucky7/preproject/question/mapper/QuestionMapper.java
server/src/main/java/com/lucky7/preproject/user/controller/UserController.java
server/src/main/java/com/lucky7/preproject/user/entity/User.java
server/src/main/java/com/lucky7/preproject/user/service/UserService.java

fix: Entity 생성, 수정 시간 annotation 추가
fix: 일부 Package 명 및 Method 명 수정

fix: Annotation 추가 및 명칭 수정

---

server/src/main/java/com/lucky7/preproject/PreProjectApplication.java
server/src/main/java/com/lucky7/preproject/answer/entity/Answer.java
server/src/main/java/com/lucky7/preproject/comment/entity/AnswerComment.java
server/src/main/java/com/lucky7/preproject/comment/entity/QuestionComment.java
server/src/main/java/com/lucky7/preproject/question/entity/Question.java
server/src/main/java/com/lucky7/preproject/user/entity/User.java

@EntityListeners를 통해 Auditing이 가능하도록 해야 @CreatedDate와 @LastModifiedDate가 정상적으로 동작합니다. 이에 수정하였습니다.

fix: Auditing 에러 수정

---

server/src/main/java/com/lucky7/preproject/answer/service/AnswerService.java
server/src/main/java/com/lucky7/preproject/comment/controller/AnswerCommentController.java
server/src/main/java/com/lucky7/preproject/comment/controller/QuestionCommentController.java
server/src/main/java/com/lucky7/preproject/comment/repository/AnswerCommentRepository.java
server/src/main/java/com/lucky7/preproject/comment/repository/QuestionCommentRepository.java
server/src/main/java/com/lucky7/preproject/comment/service/AnswerCommentService.java
server/src/main/java/com/lucky7/preproject/comment/service/QuestionCommentService.java

feat: answer, question의 id로 comment를 검색하는 기능 추가 및 오류 수정

---

server/src/main/java/com/lucky7/preproject/auth/fiter/JwtAuthenticationFilter.java
server/src/main/java/com/lucky7/preproject/auth/logindto/LoginDto.java

Fix: LoginDto 수정

---

server/src/main/java/com/lucky7/preproject/answer/controller/AnswerController.java
server/src/main/java/com/lucky7/preproject/user/controller/UserController.java
server/src/main/resources/application.yml

fix: @CrossOrigin 누락 추가 및 h2 외부 접근 허용

fix: @CrossOrigin 누락 추가 및 h2 외부 접근 허용

---

server/src/main/java/com/lucky7/preproject/answer/controller/AnswerController.java
server/src/main/java/com/lucky7/preproject/comment/controller/AnswerCommentController.java
server/src/main/java/com/lucky7/preproject/comment/controller/QuestionCommentController.java
server/src/main/java/com/lucky7/preproject/config/SecurityConfiguration.java
server/src/main/java/com/lucky7/preproject/question/controller/QuestionController.java
server/src/main/java/com/lucky7/preproject/user/controller/UserController.java
server/src/test/java/com/lucky7/preproject/PreProjectApplicationTests.java

@CrossOrigin 어노테이션 삭제, Configure에 header와 credential추가로 CORS 문제 해결 완료 
Test 부분에 여러 문제가 있어 우선 삭제 처리

fix: CORS 문제 해결, Test 삭제

---

server/src/main/java/com/lucky7/preproject/auth/jwt/JwtTokenizer.java
server/src/main/java/com/lucky7/preproject/question/dto/responseDto/QuestionCommentDto.java
server/src/main/java/com/lucky7/preproject/user/dto/UserResponseDto.java
server/src/main/java/com/lucky7/preproject/user/service/UserService.java
server/src/main/resources/application.yml

기본 crud 구현 완료했습니다
테스트 완료했습니다.
Resolves: #77

feat: User 서비스 API 구현

---

client/package-lock.json
client/package.json
client/src/components/Footer.jsx
client/src/components/Sign/SignDown.jsx
client/src/pages/Sign.jsx
client/src/utils/validationUtils.js

회원가입 페이지 기능구현 완료
회원가입 완료 후 로그인 페이지로 리다이렉트
이메일, 패스워드 유효성 검사 유틸 파일 생성

Feat: sign 페이지

---

server/src/main/java/com/lucky7/preproject/answer/controller/AnswerController.java
server/src/main/java/com/lucky7/preproject/answer/service/AnswerService.java
server/src/main/java/com/lucky7/preproject/comment/controller/AnswerCommentController.java
server/src/main/java/com/lucky7/preproject/comment/controller/QuestionCommentController.java
server/src/main/java/com/lucky7/preproject/comment/service/AnswerCommentService.java
server/src/main/java/com/lucky7/preproject/comment/service/QuestionCommentService.java
server/src/main/java/com/lucky7/preproject/config/SecurityConfiguration.java
server/src/main/java/com/lucky7/preproject/question/controller/QuestionController.java
server/src/main/java/com/lucky7/preproject/question/service/QuestionService.java

Feat: 계층별 권한 부여 완료

---

server/src/main/java/com/lucky7/preproject/answer/controller/AnswerController.java
server/src/main/java/com/lucky7/preproject/answer/service/AnswerService.java
server/src/main/java/com/lucky7/preproject/comment/controller/AnswerCommentController.java
server/src/main/java/com/lucky7/preproject/comment/controller/QuestionCommentController.java
server/src/main/java/com/lucky7/preproject/comment/service/AnswerCommentService.java
server/src/main/java/com/lucky7/preproject/comment/service/QuestionCommentService.java
server/src/main/java/com/lucky7/preproject/question/controller/QuestionController.java
server/src/main/java/com/lucky7/preproject/question/service/QuestionService.java

[ 변경 기준 ]
컨트롤러 => Http Method 명
서비스 => 기능명
Resolves: #89

refactor: 메서드명 리팩토링

---

server/src/main/java/com/lucky7/preproject/user/entity/User.java

1. 아바타 기능을 위한 추가(현재 Default image로 고정)

feat: User Entity에 avatarImg 추가

---

server/src/main/java/com/lucky7/preproject/answer/dto/responseDto/AnswerCommentDto.java

답변 조회 시 answerCommentId 조회되도록 코드 수정

fix: 답변 조회 시 answerCommentId 조회되도록 코드 수정

---

server/src/main/java/com/lucky7/preproject/answer/dto/responseDto/AnswerResponseDto.java
server/src/main/java/com/lucky7/preproject/answer/mapper/AnswerMapper.java

feat: AnswerResponseDto 필드에 avatarImg 추가

---

server/src/main/java/com/lucky7/preproject/user/dto/UserResponseDto.java

1. 아바타 기능을 위한 추가(현재 Default image로 고정)

feat: UserResponseDto에 avatarImg 추가

---

server/src/main/java/com/lucky7/preproject/auth/fiter/JwtAuthenticationFilter.java

response.addHeader를 통해 UserId 노출되도록 수정

fix: Expose-Headers 설정 수정

---

server/src/main/java/com/lucky7/preproject/comment/controller/AnswerCommentController.java
server/src/main/java/com/lucky7/preproject/comment/controller/QuestionCommentController.java
server/src/main/java/com/lucky7/preproject/comment/service/AnswerCommentService.java
server/src/main/java/com/lucky7/preproject/comment/service/QuestionCommentService.java

questionId와 commentId를 비교하는 코드 오류가 있어 수정함

fix: comment 삭제 기능 오류 수정

---

server/src/main/java/com/lucky7/preproject/config/SecurityConfiguration.java

fix: allowOrigin 추가

---

server/src/main/java/com/lucky7/preproject/answer/entity/Answer.java
server/src/main/java/com/lucky7/preproject/comment/entity/AnswerComment.java
server/src/main/java/com/lucky7/preproject/comment/entity/QuestionComment.java

fix: 질문 삭제 오류 수정

---

README.md

README.md 에 개인 프로필 이모지 추가했습니다.

fix: README.md 에 개인 프로필 이모지 추가

---

README.md

docs: README.md 화면 기능 소개 파일 깨짐 수정

docs: README.md 화면 기능 소개 파일 깨짐 수정
